dist: xenial # required for Python >= 3.7
language: python
python:
  - "3.7"
sudo: false
os:
  - linux
branches:
  only:
    - master

env:
  global:
    - secure: "f0fjpD2zugFNWJ6wQNkIAL1D5sQAuz2okQkAXoPvImyC/xmu8tXvCdbReLriqr3+OWKycxcq+VBZRq+2kQm3hmDSMUCVcGc4qK356Hjgl5akBVPQL0g7Rrf0O/1NPhvvHZu9Xq0YZOjnEGBDQ9S55FFwZyT0Db2EA7PuaTgxLfgJGOeA/cQKoS/FUhN8ldebU8zzHjHLiSo44xBAchRIDP3pcUxBRdE+Jps7RefNFIrhb7J+F/WIpe3aBtAlHhQAfBb67XsihoEzW1U2fEbsuI7NNYhsqIPZTH6S38AVhWgS5fiBizBvodZjr/toZCldO9wI6bvAe/S0YuFv4DuFsHPPoFnNOCLLIF7KqaxxkUKzaMgy1hPqZBg5KZliNcDZV9rKMNLFG5x2L4CWNw+ofS+apJsOsba+Fbau1DIGCAvlDAzxAtHaBg+J1cBgjVgyK7ITWL3qn0TC5zKdDrczXlfO0n4WXOC2ukeIjuCEj5B8PYwO+RRrt0La2uP1yB7ygRb81U5Sml0A4+R4wY4oKnn1AeHuVDxelYl/vgrfhtAyXFA4QzbOQcI7p7Q/QY4OshSUTroZmruzE7VjzRpQa8B0U9/x1JgGpuMpBYIt+6knB2Pfd7scxBknQPWgBnh6y4b9AD+mIC0iOez/WUFvlG0idi+UNcVbQ/jHN8ICMeo="
cache:
  directories:
    - $TRAVIS_BUILD_DIR/combined_lib_cache/
    - $TRAVIS_BUILD_DIR/lean-fibonacci/
    - $TRAVIS_BUILD_DIR/dist/
    - $HOME/.elan

install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - |
    if [ ! -e "$TRAVIS_BUILD_DIR/combined_lib_cache/leanpkg.toml" ]; then
      cp -av combined_lib/. combined_lib_cache
    fi
  - |
    if [ ! -e "$TRAVIS_BUILD_DIR/lean-fibonacci/leanpkg.toml" ]; then
      git clone https://github.com/bryangingechen/lean-fibonacci.git
    fi
  - source ~/.elan/env
  - source elan_setup.sh
  - mkdir $HOME/scripts || echo ""
  - export PATH="$HOME/scripts:$PATH"
  - cp travis_long.sh $HOME/scripts/travis_long
  - chmod +x $HOME/scripts/travis_long

jobs:
  include:
    - stage: Build-1
      script:
        - |
          if [ $TRAVIS_EVENT_TYPE == 'cron' ]; then
            find . -name *.olean -delete
          fi
        - elan override set leanprover-community/lean:$LATEST_BROWSER_LEAN
        - travis_long "./mk_library.py -c -o dist/libcore.zip"
        - cd combined_lib_cache
        - elan override set leanprover-community/lean:$LATEST_BROWSER_LEAN
        - leanpkg upgrade
        - rm -rf _target/deps/mathlib/test
        - rm -rf _target/deps/mathlib/scripts
        - rm -rf _target/deps/mathlib/roadmap
        - cd ..
        - travis_long "timeout 2400 ./mk_library.py -i combined_lib_cache" | python detect_errors.py

    - stage: Build-2a
      script:
        - travis_long "timeout 2400 ./mk_library.py -i combined_lib_cache" | python detect_errors.py

    - stage: Build-2b
      script:
        - travis_long "timeout 2400 ./mk_library.py -i combined_lib_cache" | python detect_errors.py

    - stage: Build-2c
      script:
        - travis_long "timeout 2400 ./mk_library.py -i combined_lib_cache" | python detect_errors.py

    - stage: Build-3
      script:
        - travis_long "./mk_library.py -i combined_lib_cache"
        # make sure we use the same version of Lean that we started with in "Build-1"
        - cd combined_lib_cache
        - ELAN_OVERRIDE=$(lean -v | cut -d ',' -f1 | cut -d ' ' -f3)
        - cd ../lean-fibonacci
        - elan override set leanprover-community/lean:$ELAN_OVERRIDE
        - git pull
        - cd ..
        - travis_long "./mk_library.py -i lean-fibonacci -o dist/libfib.zip"

    - stage: Deploy
      script:
        # make sure we use the same version of Lean that we started with in "Build-1"
        - cd combined_lib_cache
        - export ELAN_OVERRIDE=$(lean -v | cut -d ',' -f1 | cut -d ' ' -f3)
        - cd ..
        - rm -rf .git
        - sh deploy.sh
