[package]
name = "combined_lib"
version = "3.13.2"
lean_version = "leanprover-community/lean:3.13.2"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "434e6a65b8d8cc80371f7a6a835e672fa112c111"}
