[package]
name = "combined_lib"
version = "3.14.0"
lean_version = "leanprover-community/lean:3.14.0"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "79e296bdc9f83b9447dc1b81730d36f63a99f72d"}
